### ISSUE TITLE
DFM issue with production PCB

### ISSUE THREAD

**Issue by szechyjs** [sparkfun/SparkFun_u-Blox_NEO_M9N#1]
GTP is different than solder mask layer and the opening on the paste layer will cause the trace layer copper exposure.

![2020051120421858126669](https://user-images.githubusercontent.com/847739/81567349-326c5b80-936a-11ea-864d-1613d96c72bc.png)

**Comment by edspark** [comment]
You're right about the classification of the layers but I think there's a little confusion on what they do. As you mentioned the GTP is "Gerber Top Paste" and is *not* the solder stop mask layer. Solder stop as you may know, stops the mask that covers and protects the copper. The solder stop mask layer in your image is the dark pink and the light-ish pink turned into green is the **top-paste**. It is usually the case that the paste fits inside the **solder stop** because solder only adheres to exposed copper (obviously). So, looking at the image linked in your comment, I can see that the **stop layer**, stops where the traces exits the pad. So no problem there.

The GTP in production is used entirely for the stencils that apply paste. What you're seeing is *not* exposed copper but "over-pasting". We use this technique on most of  the modules in our catalog that have castellated leads. If you've seen them then you know what I'm talking about. Just in case you haven't, those castellated leads have a lot of extra metal on them that suck up a lot of solder, and so we use this technique so that we get enough paste for good solder flow all the way up the lead. 

In case you're not convinced, you can check the images we have on our [product page](https://www.sparkfun.com/products/16329), and see that the copper is *not* exposed at places where you might expect them to be. Or you can drag and drop the gerber files in this repository into this [3d Gerber Viewer](http://mayhewlabs.com/3dpcb) and get really up close to see what I'm talking about.
